### ISSUE TITLE
headless doesn't work

### ISSUE THREAD

**Issue by Patrickph** [3mora2/WPP_Whatsapp#15]
The script is only working when used with headless false, if you set it to true it stops working, I tested it on Windows machines and on 2 Linux vps and it still doesn't work

**Comment by 3mora2** [comment]
try use chromium or firefox

**Comment by Patrickph** [comment]
I've tried them all including webkit

**Comment by 3mora2** [comment]
Try show logs
And find where it break

**Comment by Patrickph** [comment]
17-Nov-23 20:45:25 - INFO - test: Initializing...
17-Nov-23 20:45:25 - INFO - test: Loading WhatsApp WEB
17-Nov-23 20:45:26 - INFO - test: WhatsApp WEB loaded
17-Nov-23 20:45:26 - INFO - test: Page loaded
17-Nov-23 20:45:26 - INFO - test: Injecting wapi.js
17-Nov-23 20:45:26 - INFO - test: Start WPPConfig
17-Nov-23 20:45:26 - INFO - test: WPPConfig
17-Nov-23 20:45:26 - DEBUG - test: start inject
17-Nov-23 20:45:26 - INFO - test: http => Waiting page load
17-Nov-23 20:45:26 - INFO - test: injected state: False
17-Nov-23 20:45:56 - ERROR - Exception in callback AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...s exceeded.')>) at C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyee\asyncio.py:69
handle: <Handle AsyncIOEventEmitter._emit_run.<locals>.callback(<Task finishe...s exceeded.')>) at C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyee\asyncio.py:69>
Traceback (most recent call last):
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyee\asyncio.py", line 77, in callback
    self.emit("error", exc)
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyee\base.py", line 211, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyee\base.py", line 169, in _emit_handle_potential_error
    raise error
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\WPP_Whatsapp\api\layers\HostLayer.py", line 63, in on_load
    await self._afterPageLoad()
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\WPP_Whatsapp\api\layers\HostLayer.py", line 80, in _afterPageLoad
    if await self.inject_api():
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\WPP_Whatsapp\api\layers\HostLayer.py", line 450, in inject_api
    await self.ThreadsafeBrowser.page_wait_for_function(
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\WPP_Whatsapp\PlaywrightSafeThread\browser\threadsafe_browser.py", line 365, in page_wait_for_function
    return await self.page.wait_for_function(expression, arg=arg, timeout=timeout, polling=polling)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\async_api\_generated.py", line 11808, in wait_for_function
    await self._impl_obj.wait_for_function(
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_page.py", line 944, in wait_for_function
    return await self._main_frame.wait_for_function(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_frame.py", line 766, in wait_for_function
    return from_channel(await self._channel.send("waitForFunction", params))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 490, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\patri\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 99, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.

**Comment by 3mora2** [comment]
iam try playwright (sync and async) not work in headless mode
[test](https://github.com/3mora2/WPP_Whatsapp/tree/main/test/test_hiden.py)

**Comment by Patrickph** [comment]
I ran the test and the error persists, I will try to use the version directly from GIT, there may be some incompatibility with the most recent version of the dependencies

**Comment by 3mora2** [comment]
i have same error 😄

**Comment by Patrickph** [comment]
So is it really a bug?

**Comment by 3mora2** [comment]
yes

**Comment by Patrickph** [comment]
Any idea how to solve it?

**Comment by 3mora2** [comment]
start with test file, open issue in [playwright-python](https://github.com/microsoft/playwright-python)

**Comment by Patrickph** [comment]
I uninstalled and reinstalled playwright and putting the firefox option worked normally

**Comment by 3mora2** [comment]
oK
