### ISSUE TITLE
Browser Opening Error - Possible Login Timeout?

### ISSUE THREAD

**Issue by Jeck-Liu-Create** [3mora2/WPP_Whatsapp#30]
I've recently encountered a problem where normally I open the browser, but sometimes the following error occurs. Could this be due to a login timeout? How can I handle it?
```
Exception in thread Thread-2 (<lambda>):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "sendmain.py", line 680, in <lambda>
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "sendmain.py", line 671, in run_async
  File "sendmain.py", line 83, in create_web_send
  File "WPP_Whatsapp\controllers\initializer.py", line 117, in start
    self.create()
  File "WPP_Whatsapp\controllers\initializer.py", line 157, in create
    is_logged = self.client.waitForLogin()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "WPP_Whatsapp\api\layers\HostLayer.py", line 313, in waitForLogin
    raise Exception("Phone not connected")
Exception: Phone not connected
```

**Comment by 3mora2** [comment]
That mean Login Done Successfully, but can't load chats:
- may be case of "deviceSyncTimeout" > (18s)
- page closed
- not Login
