### ISSUE TITLE
No such file or directory: '...playwright/driver/playwright.sh install chromium  --dry-run'

### ISSUE THREAD

**Issue by rubslopes** [3mora2/WPP_Whatsapp#39]
My code:

```python
from WPP_Whatsapp import Create

def new_message(message):
    global client
    message = message.get('body')
    chat_id = message.get('from')

    # Extract user ID and message content
    usuario_id = message.get('chatId')['user']

    print(usuario_id, message)

    client.sendText(chat_id, "Here's what you said:" + message)

if __name__ == '__main__':

    your_session_name = "test"
    creator = Create(session=your_session_name, browser='chrome')
    client = creator.start()

    # check state of login
    if creator.state != 'CONNECTED':
        raise Exception(creator.state)
    
    client.sendText('mynumber', 'Ligado')
    
    creator.client.onMessage(new_message)
```

The error:

````python
python test.py
Traceback (most recent call last):
  File "/Users/rubenslopes/Documents/repositorios/whatsapp/teste2.py", line 20, in <module>
    client = creator.start()
             ^^^^^^^^^^^^^^^
  File "/Users/rubenslopes/opt/miniconda3/envs/whatsapp/lib/python3.11/site-packages/WPP_Whatsapp/controllers/initializer.py", line 123, in start
    self.create_sync()
  File "/Users/rubenslopes/opt/miniconda3/envs/whatsapp/lib/python3.11/site-packages/WPP_Whatsapp/controllers/initializer.py", line 159, in create_sync
    self.ThreadsafeBrowser = ThreadsafeBrowser(user_data_dir=self.user_data_dir, **self.__kwargs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rubenslopes/opt/miniconda3/envs/whatsapp/lib/python3.11/site-packages/WPP_Whatsapp/controllers/browser.py", line 19, in __init__
    super().__init__(no_context=no_context,
  File "/Users/rubenslopes/opt/miniconda3/envs/whatsapp/lib/python3.11/site-packages/PlaywrightSafeThread/browser/threadsafe_browser.py", line 253, in __init__
    if install and not self.check_is_install(self._browser_name):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rubenslopes/opt/miniconda3/envs/whatsapp/lib/python3.11/site-packages/PlaywrightSafeThread/browser/threadsafe_browser.py", line 415, in check_is_install
    completed_process = subprocess.check_output(f"{driver_executable} install {browser}  --dry-run", env=env,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rubenslopes/opt/miniconda3/envs/whatsapp/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rubenslopes/opt/miniconda3/envs/whatsapp/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rubenslopes/opt/miniconda3/envs/whatsapp/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/rubenslopes/opt/miniconda3/envs/whatsapp/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rubenslopes/opt/miniconda3/envs/whatsapp/lib/python3.11/site-packages/playwright/driver/playwright.sh install chromium  --dry-run'
```

I'm running WPP_Whatsapp version 0.2.2 on MacOS. I'm running it on a conda env. This also happens if I choose firefox instead of chrome.

**Comment by rubslopes** [comment]
Running `playwright install chromium` or `playwright install firefox` does nothing, I believe they are both installed.

**Comment by rubslopes** [comment]
Running `playwright install chromium --dry-run` returns:
```
playwright install firefox --dry-run
browser: firefox version 123.0
  Install location:    /Users/rubenslopes/Library/Caches/ms-playwright/firefox-1440
  Download url:        https://playwright.azureedge.net/builds/firefox/1440/firefox-mac-13-arm64.zip
  Download fallback 1: https://playwright-akamai.azureedge.net/builds/firefox/1440/firefox-mac-13-arm64.zip
  Download fallback 2: https://playwright-verizon.azureedge.net/builds/firefox/1440/firefox-mac-13-arm64.zip
```

Maybe it is running `playwright.sh install chromium --dry-run` when it should not have the `.sh`?

**Comment by 3mora2** [comment]
You can stop auto install 
`creator = Create(session=your_session_name, browser='chrome'، install=False)`

**Comment by Patrickph** [comment]
Well now the symptom has changed, logs:

Exception in thread Thread-1 (__thread_worker):
Traceback (most recent call last):
   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.11/threading.py", line 975, in run
     self._target(*self._args, **self._kwargs)
   File "/usr/local/lib/python3.11/dist-packages/PlaywrightSafeThread/browser/threadsafe_browser.py", line 270, in __thread_worker
     self.loop.run_until_complete(self.__start_playwright())
   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
     return future.result()
            ^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/dist-packages/PlaywrightSafeThread/browser/threadsafe_browser.py", line 338, in __start_playwright
     self.context = await self.browser_type.launch_persistent_context(**self._browser_persistent_option)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/ubuntu/.local/lib/python3.11/site-packages/playwright/async_api/_generated.py", line 15075, in launch_persistent_context
     await self._impl_obj.launch_persistent_context(
   File "/home/ubuntu/.local/lib/python3.11/site-packages/playwright/_impl/_browser_type.py", line 157, in launch_persistent_context
     from_channel(await self._channel.send("launchPersistentContext", params)),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^
   File "/home/ubuntu/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 63, in send
     return await self._connection.wrap_api_call(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/ubuntu/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 495, in wrap_api_call
     return await cb()
            ^^^^^^^^^^
   File "/home/ubuntu/.local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 101, in inner_send
     result = next(iter(done)).result()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: Executable doesn't exist at /tmp/PLAYWRIGHT_BROWSERS_PATH/firefox-1438/firefox/firefox

**Comment by 3mora2** [comment]
Please try [check_is_install](https://github.com/3mora2/PlaywrightSafeThread/blob/main/PlaywrightSafeThread/browser/threadsafe_browser.py#L411) and send when work fine

**Comment by 3mora2** [comment]
I think path file break down,
like `/tmp/PLAYWRIGHT_BROWSERS_PATH/firefox-1438/firefox/firefox` check if path is exist

**Comment by Patrickph** [comment]
There are several folders in tmp, and I believe that "PLAYWRIGHT_BROWSERS_PATH" is just a variable to be replaced to choose the specific browser for that session, as there are several folders with various browsers in /tmp/.

**Comment by 3mora2** [comment]
Check [line](https://github.com/3mora2/PlaywrightSafeThread/blob/main/PlaywrightSafeThread/browser/threadsafe_browser.py#L32) i create dir and set it as playwright path

**Comment by Patrickph** [comment]
From what I analyzed, the code is correct, I believe there is some incompatibility with the Ubuntu version on my server, I will reset the server settings tomorrow and try to do a clean installation

**Comment by Patrickph** [comment]
From what I analyzed, the code is correct, I believe there is some incompatibility with the Ubuntu version on my server, I will reset the server settings tomorrow and try to do a clean installation

**Comment by rubslopes** [comment]
Thank you guys for your effort into this!

I managed to find a temporary fix:

Running `playwright install chromium --dry-run` returns this, as I mentioned earlier:

```
browser: firefox version 123.0
  Install location:    /Users/rubenslopes/Library/Caches/ms-playwright/firefox-1440
  Download url:        https://playwright.azureedge.net/builds/firefox/1440/firefox-mac-13-arm64.zip
  Download fallback 1: https://playwright-akamai.azureedge.net/builds/firefox/1440/firefox-mac-13-arm64.zip
  Download fallback 2: https://playwright-verizon.azureedge.net/builds/firefox/1440/firefox-mac-13-arm64.zip
```
So I used the install location as the `executable_path` inside the Creator call:

```python
creator = Create(session=your_session_name, browser='firefox', install=False, executable_path='/Users/rubenslopes/Library/Caches/ms-playwright/firefox-1440/firefox/Nightly.app/Contents/MacOS/firefox', headless=False)
```

**Comment by 3mora2** [comment]
temporary fix: (you don't need change `executable_path` with every browser)
```python 
creator = Create(session=your_session_name, browser='firefox', install=False, PLAYWRIGHT_BROWSERS_PATH='/Users/rubenslopes/Library/Caches/ms-playwright', headless=False)
```

OR

Update PlaywrightSafeThread `pip install PlaywrightSafeThread -U`
and use `playwright_path_env=False` to not change default path
```python 
creator = Create(session=your_session_name, browser='firefox', playwright_path_env=False, headless=False)
```

**Comment by Patrickph** [comment]
now it is working 100%
