### ISSUE TITLE
error to run example

### ISSUE THREAD

**Issue by apvdr** [3mora2/WPP_Whatsapp#48]
when i run the first example code i receive a module not found error:

Traceback (most recent call last):
  File "/home/apvdr/botTest/testbot.py", line 1, in <module>
    from WPP_Whatsapp import Create
  File "/home/apvdr/.pyenv/versions/3.11.9/lib/python3.11/site-packages/WPP_Whatsapp/__init__.py", line 2, in <module>
    from WPP_Whatsapp.api.Whatsapp import Whatsapp
  File "/home/apvdr/.pyenv/versions/3.11.9/lib/python3.11/site-packages/WPP_Whatsapp/api/Whatsapp.py", line 3, in <module>
    from WPP_Whatsapp.api.layers.HostLayer import HostLayer
  File "/home/apvdr/.pyenv/versions/3.11.9/lib/python3.11/site-packages/WPP_Whatsapp/api/layers/HostLayer.py", line 18, in <module>
    from WPP_Whatsapp.js_lib.wapi import WAPI
ModuleNotFoundError: No module named 'WPP_Whatsapp.js_lib.wapi'

**Comment by 3mora2** [comment]
ok, update now
