### ISSUE TITLE
Can i get profile image 

### ISSUE THREAD

**Issue by MominIqbal-1234** [3mora2/WPP_Whatsapp#58]
Can i get profile image user

**Comment by 3mora2** [comment]
https://wppconnect.io/wppconnect/classes/Whatsapp.html#getProfilePicFromServer

**Comment by MominIqbal-1234** [comment]
sorry but i dont understand how i use this in python

**Comment by MominIqbal-1234** [comment]
i try to all chats with mesage but its not working client.getAllChatsWithMessages()

![Screenshot from 2024-11-21 01-55-41](https://github.com/user-attachments/assets/1a677a01-8215-4348-b65a-813f5c1f9fc3)

**Comment by MominIqbal-1234** [comment]
### Not Work
```python
 print(client.loadEarlierMessages("*****@c.us"))
```


```python

Traceback (most recent call last):
  File "/home/momin/Documents/WhatsAuto/chat.py", line 150, in <module>
    print(chat.loadEarlierMessages("*****@c.us"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/Documents/WhatsAuto/chat.py", line 134, in loadEarlierMessages
    chatinfo = self.client.loadEarlierMessages(phone_number)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/WPP_Whatsapp/api/layers/RetrieverLayer.py", line 79, in loadEarlierMessages
    return self.ThreadsafeBrowser.run_threadsafe(self.loadEarlierMessages_(contactId), timeout_=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/PlaywrightSafeThread/browser/threadsafe_browser.py", line 330, in run_threadsafe
    return self.__handle_future(future, timeout=timeout_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/PlaywrightSafeThread/browser/threadsafe_browser.py", line 576, in __handle_future
    return future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/momin/.local/lib/python3.12/site-packages/WPP_Whatsapp/api/layers/RetrieverLayer.py", line 287, in loadEarlierMessages_
    return await self.ThreadsafeBrowser.page_evaluate("(contactId) => WAPI.loadEarlierMessages(contactId)",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/WPP_Whatsapp/controllers/browser.py", line 16, in wrapper
    return await method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/WPP_Whatsapp/controllers/browser.py", line 162, in page_evaluate
    return await super().page_evaluate(*args, page=page, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/PlaywrightSafeThread/browser/threadsafe_browser.py", line 538, in page_evaluate
    return await self.create_task(page.evaluate(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/PlaywrightSafeThread/browser/threadsafe_browser.py", line 309, in create_task
    return await self.loop.create_task(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/playwright/async_api/_generated.py", line 8491, in evaluate
    await self._impl_obj.evaluate(
  File "/home/momin/.local/lib/python3.12/site-packages/playwright/_impl/_page.py", line 469, in evaluate
    return await self._main_frame.evaluate(expression, arg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 278, in evaluate
    await self._channel.send(
  File "/home/momin/.local/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/momin/.local/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.evaluate: t.loadEarlierMsgs is not a function
e@https://web.whatsapp.com/ line 7 > injectedScript:1:27697
G@https://web.whatsapp.com/ line 7 > injectedScript:1:27533
a@https://web.whatsapp.com/ line 7 > injectedScript:1:27874
496/Y/Y/<@https://web.whatsapp.com/ line 7 > injectedScript:1:27933
Y@https://web.whatsapp.com/ line 7 > injectedScript:1:27813
Y@https://web.whatsapp.com/ line 7 > injectedScript:1:27948
496/window.WAPI.loadEarlierMessages@https://web.whatsapp.com/ line 7 > injectedScript:1:69343
@debugger eval code line 234 > eval:1:21
evaluate@debugger eval code:241:19
@debugger eval code:1:44


```

**Comment by 3mora2** [comment]
from [wppconnect](https://wppconnect.io/wppconnect/classes/Whatsapp.html#loadEarlierMessages.loadEarlierMessages-1)
Use `getMessages`

**Comment by MominIqbal-1234** [comment]
please explain this is chatId -> +1****456@c.us

client.getMessages("+1****456@c.us")
